### PR TITLE
Example 5 modified and parameters changed

### PR DESCRIPTION
**Pull request by agmislam1**

### CODE REVIEW

**Comment by agmislam1** [comment]
QNLP Assignment

**Comment by jaorduz** [comment]
Dear @agmislam1, It is interesting, but I would like to check the parameters that you modified, could you point out?

**Comment by agmislam1** [comment]
Dear Dr. Orduz,

Following are the changes:

sentence = 'Quantam Computing is interesting'

ansatz = IQPAnsatz({N: 2, S: 2}, n_layers=3)

Best,
Islam


Sent from my iPhone

On Apr 26, 2022, at 7:24 PM, J. A. Orduz-Ducuara ***@***.***> wrote:

﻿

Dear @agmislam1<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagmislam1&data=05%7C01%7Cagm_islam1%40baylor.edu%7C5c80073dc910428e019208da27e43f98%7C22d2fb35256a459bbcf4dc23d42dc0a4%7C0%7C0%7C637866158535469815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mCOBkxFe5phJ0AD73AJfI38Z3sJzG0jeT2Dr5K%2BhZNs%3D&reserved=0>, It is interesting, but I would like to check the parameters that you modified, could you point out?

**Comment by jaorduz** [comment]
Great! You should comment it in the NB, PDF, or assignment documentation.

**Pull request closed without merging**
