### PR TITLE
our changes in example 6. Accepted

### PR DESCRIPTION
**Pull request by rahman-mush1311**
We changed the  sentence, made a longer sentence to see the effect
We also experimented with the number of layers, reduced the layer to 1

### CODE REVIEW

**Comment by jaorduz** [comment]
@tuktuki1311, you should put your names, and point out which were the parameters that you modified.

**Comment by rahman-mush1311** [comment]
> @tuktuki1311, you should put your names, and point out which were the parameters that you modified.

@jaorduz dr orduz we changed author's names and in the commented in each section where changed it. Will you please merge it?

**Review by jaorduz — APPROVED** [review]
It looks good! I will check it!

**Comment by jaorduz** [comment]
Good!

**Pull request closed without merging**
